/** 订货系统全局配置（运行时从 Excel 数据更新 regions/categories/sizes） */
export const CONFIG = {
  historySourceFile: '历年数据.xlsx',
  baseSourceFile: '同期数据.xlsx',
  currentSourceFile: '当前数据.xlsx',
  currentSizeDetailSourceFile: '当前数据尺码明细.xlsx',
  otbSourceFile: 'OTB.xlsx',
  sizes: [],
  allSizes: [],
  colorSeries: [],
  fits: [],
  fabrics: [],
  categories: [],
  subCategories: [],
  genders: [],
  historyStyleNos: [],
  historyArticleNos: [],
  years: [],
  seasons: [],
  regions: [],
  brands: [],
  currentBrands: [],
  currentGenders: [],
  currentSubCategories: [],
  currentFits: [],
  currentFabrics: [],
  currentColorSeries: [],
  currentStyleNos: [],
  compareYears: ['同期', '当前'],
  salesToOrderRatio: 0.75,
  purchaseRate: 0.37,
  storageKey: 'order-system-orders',
  dbPath: 'data/orders.db',
};

/** 各模块数据来源说明（file 指向 CONFIG 中对应字段） */
export const DATA_SOURCES = {
  overviewBase: { configKey: 'baseSourceFile', scope: '概览·同期' },
  overviewCurrent: { configKey: 'currentSourceFile', scope: '概览·当前' },
  history: { configKey: 'historySourceFile', scope: '历史数据' },
  orderCatalog: { configKey: 'currentSourceFile', scope: '订货单·商品/订货量' },
  orderSizeDetail: { configKey: 'currentSizeDetailSourceFile', scope: '订货单·尺码合计/明细' },
  createCatalog: { configKey: 'currentSourceFile', scope: '新建订货·商品/货号/订货量' },
  createRecommend: { configKey: 'historySourceFile', scope: '新建订货·智能推荐' },
};
